# .github/workflows/ci.yml
name: 'CI Pipeline'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./terraform
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
          terraform_wrapper: false
          
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Apply
        env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve -input=false

      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed - Check AWS Academy session"
            exit 1

      - name: Cleanup with Terraform Destroy
        if: always()
        run: |
          echo "💡 Starting Terraform destroy..."
          terraform destroy -auto-approve
          echo "✅ Cleanup complete"
